### ISSUE TITLE
Dokumente in goMobile Pro bearbeiten

### ISSUE THREAD

**Issue by PeterLindemann** [GEDYSIntraWare/Anpassungsleitfaden-goMobilePro#3]
In der Dokumentation steht in der aktuellen Version dies: 
> Der neue InAppEditmode benutzt analog zum Lesemodus einen sogenannten 'editStyle'. Es gibt zusätzlich die Möglichkeit einen 'editSubStyle' mit Hilfe des Components 'EditSubform' zu verwenden.

Ich habe in der app_customization die function cuGetEditSubStyle(object) um fieldDefinitions für eine neue Subform erweitert.
Das klappt auch wunderbar, allerdings offenbar nur mit einzelnen Feldern.

Unsere passende Teilmaske in Notes bzw. das CustomControl für den Webclient enthält allerdings mehrere Sektionen, ist also komplexer als nur einzelne Felder.
Also habe ich versucht in der function cuGetEditSubStyle(object) dieser eigenen Subform eine weitere property "component": "EditSubform" einzufügen in der dann erst die fieldDefinitions enthalten sind.
Das Resultat ist, dass die App im EditMode nur noch eine weiße Seite anzeigt.

Der Config-REST-Service über http://server.tld/pfad/Mobileint.nsf/rest.xsp/config?type=all zeigt keine Fehlermeldung an.

Ist der Satz in der Dokumentation so zu verstehen, dass der 'editSubStyle' selbst bereits eine "component": "EditSubform" ist, deshalb keine weitere "component": "EditSubform" enthalten darf?

Falls dies so ist wäre mein Vorschlag für eine Umformulierung
> Der neue InAppEditmode benutzt analog zum Lesemodus einen sogenannten 'editStyle'. Es gibt zusätzlich die Möglichkeit einen 'editSubStyle' zu verwenden, welcher auf einer Component 'EditSubform' basiert, also nur Felder enthalten darf.

**Comment by NiklasMerz** [comment]
Vielen Dank für das Ticket. Was Sie festgestellt haben ist vollkommen richtig. goMobile Pro unterstützt innerhalb von EditSubforms keine weitern EditSubforms. `editSubStyles` werden wie intern in einem EditSubform Component verarbeitet deswegen kann man folgerichtig keine weiter verschachtelten EditSubforms verwerden.

Ich hab das in einem Pull Request #4 entsprechend beschrieben. Dabei ist mir aufgefallen dass die Inputs von EditSubform für die Verwendung von editSubstyles komplett in der Doku gefehlt haben. Diese Verbesserungen werden mit dem nächsten Update der Dokumentationsseite sichbar sein.

Weiteres Feedback ist natürlich Willkommen.

**Comment by PeterLindemann** [comment]
Vielen Dank für die schnelle Reaktion und Ihr Feedback!
