### ISSUE TITLE
Property-Bezeichnung "fieldDefintions"

### ISSUE THREAD

**Issue by PeterLindemann** [GEDYSIntraWare/Anpassungsleitfaden-goMobilePro#5]
In den Beispielen im Leitfaden wird zum Anpassen oft die Property "fieldDefinitions" verwendet.
Allerdings gibt es in der "app_getConfig.js" bei dieser Property an mehreren Stellen einen Schreibfehler, denn dort fehlt im Bezeichner der Property ein "i" ("fieldDefin(i)tions").
Der Schreibfehler existiert in der Version GI8.10 IUI#3 und auch in der aktuellen Version 8.11 der ScriptLib an mehreren Stellen.
Ein Hinweis im Leitfaden wäre hilfreich, da ich das fehlende "i" oft überlesen habe. Dieser könnte ja wieder entfallen wenn der Schreibfehler in der ScriptLib korrigiert wurde.
Ob es auch noch in anderen Properties in der "app_getConfig.js" einen Schreibfehler gibt ist mir zumindest nicht aufgefallen.

**Comment by NiklasMerz** [comment]
Dieser Tippfehler ist uns auch aufgefallen und wurde kürzlich in goMobile Pro behoben. Die fehlerhafte Schreibweise war nur bei den fieldDefinitions von EditStyles. **Ab dem nächsten Update kann die App mit beiden Schreibweisen umgehen**. An anderen Stellen wie bsw. EditSubform ist die Schreibweise korrekt.

In einer zukünftigen Version von GEDYS IntraWare 8 wird dieser Tippfehler auch in der Standardefinition behoben sein.
